#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-/users/project1/pt01315/emnlp/grm_media}"
PYTHON="${PYTHON:-/users/scratch1/dancies/conda_envs/py312/bin/python}"

INPUT_DIR="${INPUT_DIR:-${ROOT}/results/refiner_zoo_uncert}"
OUT_DIR="${OUT_DIR:-${ROOT}/results/tail_risk_nested_eps001}"
SELECTION_MODE="${SELECTION_MODE:-nested}"
HARM_EPS="${HARM_EPS:-0.01}"
NESTED_SELECT_FRACTION="${NESTED_SELECT_FRACTION:-0.25}"
NESTED_CAL_FRACTION="${NESTED_CAL_FRACTION:-0.25}"
REQUIRE_POSITIVE_UTILITY="${REQUIRE_POSITIVE_UTILITY:-1}"
MIN_CAL_UTILITY="${MIN_CAL_UTILITY:-0.0}"

PYTHON="$PYTHON" \
INPUT_DIR="$INPUT_DIR" \
OUT_DIR="$OUT_DIR" \
SELECTION_MODE="$SELECTION_MODE" \
HARM_EPS="$HARM_EPS" \
NESTED_SELECT_FRACTION="$NESTED_SELECT_FRACTION" \
NESTED_CAL_FRACTION="$NESTED_CAL_FRACTION" \
REQUIRE_POSITIVE_UTILITY="$REQUIRE_POSITIVE_UTILITY" \
MIN_CAL_UTILITY="$MIN_CAL_UTILITY" \
COPY_TABLES="${COPY_TABLES:-0}" \
bash "${ROOT}/tools/run_tail_risk_primary_suite.sh"
